### ISSUE TITLE
scrollProgress gives negative values (up to -7)

### ISSUE THREAD

**Issue by violoncelloCH** [jeremenichelli/scrollProgress#6]
I want to use scrollProgress for a simple Indicator. But if I load the page it starts at 0 and goes into negative when I'm scrolling down. If I resize the window the script seems to recalculate the page height and the value is corect ( 0 - 1 ) now.
Could you give me a hint how I could trigger this after pageload?

**Comment by jeremenichelli** [comment]
Hi there, super weird to hear about a negative outcome of the calculations, but I guess it's possible depending on the context the library is running.

It seems to me that you're initializing the observer way before the page has finished loading.

The solution would be to move code that contains this approach at the bottom of the body tag so it runs after DOM is ready. Also you can do that inside a window load event, like this:

```js
window.addEventListener('load', (e) => {
  const observer = new ScrollProgress((x, y) => console.log('do something cool');
});
```

As a hacky thing, you can try to run, again at the end of all your code, the private `_onResize` method in the instance, like this:

```js
observer._onResize();
```

But honestly I would leave that in case absolutely nothing works since that method is private and can change in the future and break your code.

Moving the observer creation at the end of your code and the load event thing should be enough.

**Comment by violoncelloCH** [comment]
Thank you very much! 
`window.addEventListener` is the best solution for my case and works perfectly. 

Now I'd like to use the output of `scrollProgress` to calculate a number at two positions on the page.

    const progressElement = document.querySelector('.finish-time');
    window.addEventListener('load', (e) => {
	const progressObserver = new ScrollProgress((x, y) => {
		progressElement.innerHTML = y;    
	});
    });

in html there are two elements with `class="finish-time"`
I couldn't find a method to address two elements which didn't break the functionality (no output at all). I tried e.g. `.querySelectorAll()` and `getElementsByClassName()`.

**Comment by jeremenichelli** [comment]
First, glad the load event worked out. I'm closing this issue then.

About the second thing, it is not possible to save two DOM elements in one single reference, you will have to use either `querySelectorAll` or `getElementsByClassName` and do:

```js
const progressElements = document.getElementsByClassName('.finish-time');

// rest of your code...

progressElements[ 0 ].innerHTML = y;
progressElements[ 1 ].innerHTML = y;
```

**Comment by violoncelloCH** [comment]
Of course, sorry for not closing it...

Thank you very much, I did not know the `[ 0 ] / [ 1 ]`-thing. Now it works like a charm!
