### ISSUE TITLE
React Component dynamic update

### ISSUE THREAD

**Issue by valentinniji** [jeremenichelli/scrollProgress#8]
In React, when we have dynamic component with fetch API, the height (or width) or not the same as height in componentDidMount()

To correct the problem, you can recalculate the viewportheight and viewportwidth in getProgress.

Regards

**Comment by jeremenichelli** [comment]
Temporarily you can use `yourScrollProgressInstance._onResize()` and later `yourScrollProgressInstance.trigger()` to fix this situation inside your React component, the only caveat around this is that `_onResize` is not part of the public API and it could change in the future, but as a quick fix feel free to do it.

Recalculating all the metrics inside the progress algorithm is not good since you will be triggering layout in some browsers during scroll, so performance wise it's better to keep it outside the calculation process.

Let me know if my approach works for you :)
